### ISSUE TITLE
Mobile Hamburger Follow Scroll?

### ISSUE THREAD

**Issue by doubleofive** [jaysylvester/comitium#127]
I think it would be helpful for the Hamburger Menu Bar on the mobile site to stay at the top while you scroll down. This would prevent having to depend on the "to the top" button to avoid swiping like an insane person to get back to the top.

**Comment by jaysylvester** [comment]
See #112, which is basically what you're asking for, except the header appears when the user scrolls up. Saves a bit of space on small mobile screens.

Also, props for calling it a hamburger.

**Comment by doubleofive** [comment]
That's what I get for not searching first. I have dabbled in design, but I
learned that phrase from an article complaining how we depend on them too
much. I love hamburgers, digital and physical.

**Comment by jaysylvester** [comment]
Closing this since #112 covers the use case. Still shooting for 0.1.0 release.
