### ISSUE TITLE
Clicking on fancy new OT logo in the top bar logs me out

### ISSUE THREAD

**Issue by doubleofive** [jaysylvester/comitium#137]
No matter which page I'm on, clicking on the home button logs me off.

**Comment by doubleofive** [comment]
This happens on all of my various Apple devices I can test from.

**Comment by doubleofive** [comment]
Seems to be working properly this morning from iPad.

**Comment by jaysylvester** [comment]
The URL update I made last night resolved this issue, which was caused by the login cookie path.
