### ISSUE TITLE
Mysterious Box floating in vertical mode on iPad

### ISSUE THREAD

**Issue by doubleofive** [jaysylvester/comitium#139]
![image](https://cloud.githubusercontent.com/assets/13989212/9892785/22a7d196-5be0-11e5-93ff-8e0376a37fdd.png)
![image](https://cloud.githubusercontent.com/assets/13989212/9892786/22a808dc-5be0-11e5-911b-5d4213e9ec3d.png)

**Comment by doubleofive** [comment]
It looks like it's a Private Messages drop down that stays dropped in vertical. This was not an issue last beta.

**Comment by doubleofive** [comment]
It was the new PM notification! While no longer mysterious, it should be moved so it can be read

**Comment by jaysylvester** [comment]
It's actually a menu for your account (which includes a link to private topics).

Is that Chrome? I have no way of testing that on an iPad. Chrome for Android has the menu in the correct position, as does Safari. Can you check it in Safari? I tested that on an iPad simulator, but not an actual iPad.

**Comment by doubleofive** [comment]
It was the same in Safari, I checked. Chrome on iPad is just a wrapper, the
actual rendering is the same as Safari. Send me a PM and I can check again.

**Comment by doubleofive** [comment]
I forgot, I'm on the beta for iOS 9.1 currently, I may have to hold off on
reporting things. However, I can check on my wife's iPad which is still on
8.4.1.

**Comment by doubleofive** [comment]
Warb  sent me one, testing

**Comment by doubleofive** [comment]
iOS 9.1 Beta:
![image](https://cloud.githubusercontent.com/assets/13989212/9894423/b334198e-5bf1-11e5-965e-7628decbec50.png)

iOS 8.4.1:
![image](https://cloud.githubusercontent.com/assets/13989212/9894427/bfa29a38-5bf1-11e5-84a4-371c2d8be892.png)

**Comment by doubleofive** [comment]
It is always there when viewing in vertical orientation. Once the message has been read, it goes away.

Anything else I can do? Besides buy you an iPad? ;-)

**Comment by jaysylvester** [comment]
Nope, found it. You were right, it only shows up when you have updates, and only when the display width is medium-sized (tablet). Disappears once you've read your messages. Good catch.

**Comment by jaysylvester** [comment]
Fixed on test. Looks good to me, but please verify.

**Comment by doubleofive** [comment]
Confirmed fixed.
