### ISSUE TITLE
Post Edit History Blocking

### ISSUE THREAD

**Issue by Danfun64** [jaysylvester/comitium#140]
@TVsFrink and @jaysylvester both desire a post edit history feature (#4 and #13 respectively). However, should that be allowed for every post? Many times posts are edited to remove copyright infringing links, or embarrasing information. How should those cases be handled?

**Comment by jaysylvester** [comment]
I think Frink's reference to "post history" only meant being able to view a member's collection of posts, not the history of individual posts (he can chime in if I'm mistaken). The operative phrase in my description of the feature in #13 is "available to the post author and moderators", meaning that I envisioned the ability to view previous post versions as a feature available only to the original author and moderators, not other members or the general public.

**Comment by Danfun64** [comment]
Since "post history" as you and Frink describe has already been implanted, this issue is nonexistent. Closing...

**Comment by TVsFrink** [comment]
Probably none of my business, but is Danfun helping you with the new site?

**Comment by jaysylvester** [comment]
It's currently a one-man show, but since it's open source, anyone can contribute (as soon as I create a setup script to create the dev environment).
