### ISSUE TITLE
Signatures should be left-justified by default

### ISSUE THREAD

**Issue by ProjectThreepio** [jaysylvester/comitium#147]

**Comment by ProjectThreepio** [comment]
After having lived in the new environment for a while, I kinda see now why signatures were right-justified, to allow them to be more easily distinguished from normal post content.  However, I think there must be some other way to mark signatures as distinct from posts via some alternate style without right-justification.  Multi-line text signatures just look wrong right-justified.  Single-line text and image-only signatures are fine.

**Comment by jaysylvester** [comment]
No plans to change this any time soon. Right justification is as much about getting people to minimize their signatures as it is to distinguish them from post content.

You ever see a car with way too many bumper stickers? The problem isn't that the car needs a bigger back end :)
