### ISSUE TITLE
Thread list page should list who made the last post, in addition to the time

### ISSUE THREAD

**Issue by ProjectThreepio** [jaysylvester/comitium#148]
For some threads, people are just waiting and chatting for big announcements from one person (i.e. Harmy).  In others, one person posts most of the messages, but wants to quickly know when someone else posts (i.e. CatBus).  For other threads, it probably doesn't matter as much, but knowing WHO made the last post is occasionally very relevant information.

**Comment by Feallan** [comment]
+1
The time of the last post is important too for anyone that logs in a couple times a day.

**Comment by jaysylvester** [comment]
Fixed in last update.
